name: Simple Build Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  simple-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Add timeout
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Test import
      run: |
        python -c "import anonsuite; print('✓ Import successful')"

    - name: Test CLI
      run: |
        python -m anonsuite --version
        python -m anonsuite --help