name: Simple Build Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  simple-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Add timeout
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'  # Added Python version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || echo "No requirements.txt found, skipping"
        
    - name: Run tests
      run: |
        # Add your test commands here
        pytest || echo "No tests or pytest not installed, skipping"
        
    - name: Build package
      run: |
        # Add your build commands here
        python setup.py build || echo "No setup.py found, skipping"
