name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Lint with ruff
      run: |
        ruff check src/ --exclude src/wifi/wifipumpkin3/
        ruff format src/ --check --exclude src/wifi/wifipumpkin3/
    - name: Type check with mypy
      run: |
        mypy src/ --ignore-missing-imports --exclude src/wifi/wifipumpkin3/ || echo "Type checking completed with warnings"
      continue-on-error: true
    - name: Test with pytest
      run: |
        pytest tests/ --maxfail=5 -x
      continue-on-error: true
